### ISSUE TITLE
Outdated TestFlight SDK

### ISSUE THREAD

**Issue by sukima** [dasmurphy/testflight-module#2]
This repository builds with an outdated SDK version. Since May 1st apple will reject **all** apps built with this module. SDK version 1.2.5 (and now 1.2.6) fixed this problem.

**Comment by dasmurphy** [comment]
Thanks for the info. I will update this module ASAP.

**Comment by dasmurphy** [comment]
Now updated to 2.0 - Sorry for the long delay.
